blog/urls.py
from django.urls import path

from blog.apps import BlogConfig

from blog.views import (
    BlogListView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView, BlogListViewAll
)

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('listAll/', BlogListViewAll.as_view(), name='blog_list_all'),
    path('<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('list/', BlogListView.as_view(), name='blog_list'),
    path('<int:pk>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete'),
    path('blog/create', BlogCreateView.as_view(), name='blog_create')
    ]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.text import slugify

NULLABLE = {'null': True, 'blank': True}


class Blog(models.Model):
    title = models.CharField(max_length=200, verbose_name="Заголовок")
    slug = models.CharField(unique=True, max_length=200, verbose_name="Ссылка")
    content = models.TextField(verbose_name="Содержимое")
    preview_image = models.ImageField(upload_to='blog/', **NULLABLE, verbose_name="Превью")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    is_published = models.BooleanField(default=False, verbose_name="Опубликовано")
    view_count = models.PositiveIntegerField(default=0, verbose_name="Просмотры")

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import Blog


class BlogListViewAll(ListView):
    model = Blog


class BlogListView(ListView):
    model = Blog

    def get_queryset(self):
        return Blog.objects.filter(is_published=True)


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.view_count += 1
        obj.save()
        return obj


class BlogCreateView(CreateView):
    model = Blog
    fields = ['title', 'content', 'preview_image', 'is_published']
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_slug = form.save()
            new_slug.slug = slugify(new_slug.title)
            new_slug.save()

        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ['title', 'content', 'preview_image', 'is_published']

    # success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_slug = form.save()
            new_slug.slug = slugify(new_slug.title)
            new_slug.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')

blog/templates/blog/blog_confirm_delete.html
{% extends "catalog/base.html" %}

{% block content %}
<body>
    <div class="container mt-5">
        <h1>Вы уверены, что хотите удалить "{{ blog.title }}"?</h1>
        <form method="post">
            {% csrf_token %}
            <button type="submit" href="{% url 'blog:blog_list' %}" class="btn btn-danger">Да, удалить</button>
        </form>
        <a href="{% url 'blog:blog_list' %}" class="btn btn-secondary mt-3">Нет, отменить</a>
    </div>
</body>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends "catalog/base.html" %}

{% block content %}
<body>
    <div class="container mt-5">
        <h1>{{ blog.title }}</h1>
        {% if blog.preview_image %}
            <img src="{{ blog.preview_image.url }}" alt="Preview" class="img-fluid">
        {% else %}
            <p>Нет изображения</p>
        {% endif %}
        <p>{{ blog.content }}</p>
        <p>Ссылка: {{ blog.slug }}</p>
        <p>Создан: {{ blog.created_at }}</p>
        <p>Опубликовано: {% if blog.is_published %}Да{% else %}Нет{% endif %} </p>
        <p>Просмотров: {{ blog.view_count }}</p>
        <a href="{% url 'blog:blog_update' blog.pk %}" class="btn btn-secondary">Редактировать</a>
        <a href="{% url 'blog:blog_delete' blog.pk %}" class="btn btn-danger">Удалить</a>
        <a href="{% url 'blog:blog_list' %}" class="btn btn-primary">Обратно к списку</a>
    </div>
</body>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends "catalog/base.html" %}

{% block content %}
<body>
<div class="container mt-5">
    <h1>Создать/редактировать сообщение в блоге</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">
            {% if object.pk %}
            Изменить
            {% else %}
            Создать
            {% endif %}
        </button>
        <button href="{% url 'blog:blog_list' %}" class="btn btn-secondary" >Отмена</button>

    </form>
</div>
</body>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends "catalog/base.html" %}

{% block content %}
<body>
    <div class="container mt-5">
        <h1>Посты(опубликованные)</h1>
        <a href="{% url 'blog:blog_create' %}" class="btn btn-primary mb-3">Создать новый пост</a>
        <a href="{% url 'blog:blog_list_all' %}" class="btn btn-primary mb-3">Показать все посты</a>
        <ul class="list-group">
            {% for blog in object_list %}
                <li class="list-group-item">
                    <a href="{% url 'blog:blog_detail' blog.pk %}">{{ blog.title }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
</body>

{% endblock %}